<template>
  <div class="bg-white">
    <div class="max-w-2xl mx-auto">
      <div class="space-y-6">
        <div>
          <label for="description" class="block text-sm font-medium text-gray-700">
            Note(Place the asteriks* around the start and the end of the note description))
          </label>
          <div class="mt-1">
            <textarea :disabled="note.id" v-model="note.content" id="description" name="description" rows="6" class="block w-full shadow-sm focus:ring-gray-500 focus:border-gray-500 sm:text-sm border border-gray-300 rounded-md"></textarea>
          </div>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 pt-2 pb-16 sm:px-6 sm:pt-4 sm:pb-24 lg:px-8 xl:px-2 xl:pt-4">
      <h1 class="sr-only">Checkout</h1>

      <div class="max-w-lg mx-auto grid grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2">
        <div class="max-w-lg mx-auto w-full">
          <h2 class="sr-only">Order summary</h2>

          <div class="flow-root hidden">
            <ul role="list" class="-my-6 divide-y divide-gray-200">
              <li v-for="product in products" :key="product.id" class="py-6 flex space-x-6">
                <div class="flex-auto">
                  <div class="space-y-1 sm:flex sm:items-start sm:justify-between sm:space-x-6">
                    <div class="flex-auto text-sm font-medium space-y-1">
                      <h3 class="text-gray-900">
                        <a :href="product.href">{{ product.name }}</a>
                      </h3>
                      <p class="text-gray-900">{{ product.price }}</p>
                      <p class="hidden text-gray-500 sm:block">{{ product.color }}</p>
                      <p class="hidden text-gray-500 sm:block">{{ product.size }}</p>
                    </div>
                    <div class="flex-none flex space-x-4">
                      <button type="button" class="text-sm font-medium text-indigo-600 hover:text-indigo-500">Edit</button>
                      <div class="flex border-l border-gray-300 pl-4">
                        <button type="button" class="text-sm font-medium text-indigo-600 hover:text-indigo-500">Remove</button>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>

          <dl class="text-sm font-medium text-gray-500 mt-4 space-y-2">
            <div v-for="item in items" :key="item">
              <div class="flex justify-between">
                <dt>{{ item.split(/\+|\-/)[0] }}:</dt>
                <dd class="text-gray-900 text-lg tracking-largest">{{ resultsFilterer(item.split(/\w+/)[1]) }}</dd>
              </div>
            </div>

            <div class="flex justify-between border-t border-gray-200 text-gray-900 pt-6">
              <dt class="text-base">Provided Total</dt>
              <dd class="text-base">{{ providedTotal }}</dd>
            </div>
            <div class="flex justify-between border-t border-gray-200 text-gray-900 pt-6">
              <dt class="text-base">Autogenerated Total</dt>
              <dd class="text-base">$126.32</dd>
            </div>
          </dl>
        </div>

        <form class="mt-1">
          <div class="max-w-lg mx-auto w-full">
            <div class="mt-1">
              <label for="email-address" class="block text-sm font-medium text-gray-700">Note Description</label>
              <div class="mt-1">
                <textarea v-model="note.description" name="email-address" class="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"></textarea>
              </div>
            </div>

            <div class="relative mt-1">
              <div class="absolute inset-0 flex items-center" aria-hidden="true">
                <div class="w-full border-t border-gray-200"></div>
              </div>
              <div class="relative flex justify-center">
                <span class="px-4 bg-white text-sm font-medium text-gray-500">
                  Note items
                </span>
              </div>
            </div>
              <div class="mt-1">
                <label for="email-address" class="block text-sm font-medium text-gray-700">Email address</label>
                <div class="mt-1">
                  <input type="email" id="email-address" name="email-address" autocomplete="email" class="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" />
                </div>
              </div>

              <div class="mt-1">
                <label for="phone" class="block text-sm font-medium text-gray-700">Phone number</label>
                <div class="mt-1">
                  <input type="text" name="phone" id="phone" autocomplete="tel" class="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" />
                </div>
              </div>

              <div class="flex justify-end mt-2">
                <button type="button" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                  Cancel
                </button>
                <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-900 hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                  Save this note
                </button>
              </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
const products = [
  {
    id: 1,
    name: "Women's Basic Tee",
    href: '#',
    price: '$32.00',
    color: 'Gray',
    size: 'S',
    imageSrc: 'https://tailwindui.com/img/ecommerce-images/checkout-page-05-product-01.jpg',
    imageAlt: "Front of women's basic tee in heather gray.",
  },
  // More products...
]

export default {
  data() {
    return {
      products,
      note: {
        id: null,
        description: "",
        items: [],
        score: 0,
        error: 0,
        content: "*Expressive/Pragmatic Language - book (the tiny seed)\nSTG2: named vocabulary in pictures -visual/verbal/max cues*\nsun -+\nfish +\nseed +\nbird - -\ngrass +\nsnow -\nrain-\nfoot -\nflower - -\ntree +\nTotal: 5/13=38%",
      }
    }
  },
  computed: {
    items() {
      // item.toLowerCase().match(/^errors/) || 
      return this.note.content.split("\n").filter((item) => {
        return !(item.toLowerCase().match(/^\*|\*$/) || item.toLowerCase().includes('total'))
      })
    },

    providedTotal() {
      let pt = (this.note.content.split("\n").filter((item) => {
        return item.toLowerCase().includes('total')
      })[0]|| '').toLowerCase()

      console.log(!!pt, "loud world")

      if(!pt) {
        return "Not provided"
      } else {
        return pt.split("total")[1].replace(/\:|\%/g, "")
      }
    }
  },
  methods: {
    resultsFilterer(chars) {
      if(chars.indexOf(' ') >= 0 || chars.indexOf(':') >= 0 ) {
        return chars.replace(/\s|\:/g, '')
      } else {
        return chars
      }
    },
    totaller() {
      return this.note.content.split("\n").filter((item) => {
        return item.toLowerCase().includes('total')
      })
      // this.items().each().split(/\w+/)[1].replace(/\s|\:/g, '')
    }
  }
}
</script>
